#!/usr/bin/env bash
# Scaffold a new Obsidian vault for the AI memory system.
# Usage: ./setup-vault.sh <vault-path>

set -euo pipefail

VAULT="${1:-}"
if [[ -z "$VAULT" ]]; then
    echo "usage: $0 <vault-path>" >&2
    exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TEMPLATES="$SCRIPT_DIR/templates"

if [[ -e "$VAULT" && -n "$(ls -A "$VAULT" 2>/dev/null || true)" ]]; then
    echo "vault path '$VAULT' already exists and is non-empty; refusing to overwrite" >&2
    exit 1
fi

mkdir -p "$VAULT"/{vault,vault/SKILLS,daily,inbox,people,work,personal,archive}

cp "$TEMPLATES/MEMORY.md"          "$VAULT/MEMORY.md"
cp "$TEMPLATES/USER.md"            "$VAULT/USER.md"
cp "$TEMPLATES/vault/ENVIRONMENT.md"     "$VAULT/vault/ENVIRONMENT.md"
cp "$TEMPLATES/vault/PROJECTS.md"        "$VAULT/vault/PROJECTS.md"
cp "$TEMPLATES/vault/TROUBLESHOOTING.md" "$VAULT/vault/TROUBLESHOOTING.md"
cp "$TEMPLATES/vault/SKILLS-INDEX.md"    "$VAULT/vault/SKILLS/INDEX.md"

cp "$SCRIPT_DIR/.env.example" "$VAULT/.env.example"

cat > "$VAULT/.gitignore" <<'EOF'
.env
.obsidian/workspace*
.obsidian/cache
EOF

cat > "$VAULT/README.md" <<EOF
# Vault

Generated by obsidian-memory on $(date -u +%Y-%m-%dT%H:%M:%SZ).

- \`MEMORY.md\` and \`USER.md\` are tier-1 hot memory (injected every turn).
- \`vault/\` is tier-2 living files (read on demand).
- \`daily/\` is tier-3 daily notes (timeline of every decision).
- \`inbox/\` is unclassified incoming — sweep weekly.
EOF

echo "vault scaffolded at: $VAULT"
echo
echo "next:"
echo "  cp $VAULT/.env.example $VAULT/.env  # then edit"
echo "  VAULT=$VAULT $SCRIPT_DIR/scripts/generate-daily-note.sh"
